[phases.setup]
nixPkgs = ['...', 'nodejs', 'npm']

[phases.build]
cmds = [
    'composer install --no-dev --optimize-autoloader --classmap-authoritative',
    'npm ci',
    'npm run build',
    'node generate-icons.cjs'
]

[start]
cmd = 'bash start.sh'
